language: java
jdk:
   - oraclejdk9
addons:
  sonarcloud:
    organization: AlessDea
    token:
      secure: "pr/nBoRjLYdWQu4hTlbqnpeadkGaYHwIcEkhAAckD3Tujp7GqJH2nYMfcvAsj6kLrRhuuPKz8s35mksBQaJkWbPPDXFCOtdrbNzgOWqHCKiIKR+yRNF1yjhktyY3rV1xhVRcI49j0TW+nmVDYAh+6b4DBMN4n+2nApjMIC3aWVLqLFKcuBY6hQRSapzkkaJIiGQ3X4jsHmshCEIT+2H3V+0TPkJAIOuKBlWESRKypi6cVmZ0g1CrWce5madK5SbuwXxh+oCqcrFeNQvs3//smmulekB+eabX9JJ4kVc3zzfQ1LJjvoAAYx8UKOP+Z4e77zu1N7BJ2KqSFeE/le64RZJ6emrP6wT/54+HaLBDAydOaHHweLOYpNVB44KoGdYBkIqvP1s9lDbSDEoQB1A2DPESbLF4kz973YIkzsLeECzzS44eZE+/j8ahGlRVsyzKWqJHwgUGb2Q6waJ+XIC96w8fgOelbvoW0DgKniT6PMUtmJNlr0R1xXzC2HZf1E0zwCMufERCP/rpbenGC33g8yO5QDm+lUDLGbBPv27oiXjuO0/hp+B+5LsJGr/S8SCJNI/kV//rwq956WdivOUlfIgRwXPCZo0qwFPH39G9pRpZX0B8gMs58rB2NDa7v5n4/39+SmbVh9FOIQiJUiUXTk8bqjqUIxchL7J8iTX6iU8="
script:
- ant build
- sonar-scanner
