language: java
jdk:
   - oraclejdk9
addons:
  sonarcloud:
    organization: AlessDea
    token:
      secure: "YOY2h/o4X5GY/SRL7qsJszPGQBUG9bAGBXz+xcqtblQ4aH6XkN7D4tCVRejh4I5KUvANrkzii9rsEOMqRaeXTb5XstMEt0gzq1C+JFm0ro1dn8kgjOLpm/rksIkyBc0HV6NjRKNqmKjAMxh3iN+vkldeVFoqLnu86/1LHpBAwkAFulsNqEvB5NSxzQGkxxED/+NfS3HmCVTUcaS0nyO0g0En+5jlAeCLNyg+8Bpkk5B6mnGV5kpm8Fi58S3MgdmQyF1KK8/Gg/SMrj88LGd2J9iiVE0GZeaUMtm0Wor4Y3baQ6HlWD8BnUpBYXEJu+n5Hz1HZNoWUaD7pSiYBDA5MYqOaaqEnaCGe3THsKqYBfGFZDGYL0yRJVQZkrVbnq+AfR5D3GG1s1+x9lfeAqffbm1lEoc1E+lSiPyHL277JJ4bSIKBh2Y7QWOx8Wr5EH30QfxNt+Ms/NmxWeRqMYKJf+eTF0hynnSUgCcEuUlEBVyCMh4cFyPRKI4Pju0C7fuv6/OJk3dZdabM3TEyxhyLkXF3mEhUyx0QLi95xdODU1EW0opyRXvGLSX8+rr5tX/aRHN7C26F7tnjjyHeOxFSnsk05X74npMUb1dpN3p7DuzdowEFATh2H0Oke3hoPns9s3XE/epEYApCfannAiepD2Eg/CexsloXW+csPEwd3No="
script:
- ant build
- sonar-scanner
