language: java
jdk:
   - oraclejdk9
addons:
  sonarcloud:
    organization: alessdea
    token:
     secure: travis encrypt bb6709d5a73398c743dab150da03c83b54830d4e
script:
- ant build
- sonar-scanner
