language: java^M
jdk:^M
   - oraclejdk9^M
addons:^M
  sonarcloud:^M
    organization: AlessDea^M
    token:^M
      secure: "1lREidZ3AUqsT5k4PXuVMGMUxkKYlvs3F6QfR0TtTBeEumfpPDrmmDdI47UsvIOXqMVKAMk2S6PkFIfPPjsQWhTPbDzCJZbuuPRkZnRd1gTEq1JBObL7h4l6wY86Tcr1Z3m+ZNopqNkjeIqboacEi5oWVsiyWJWtyxo1ScwKjwE8dQXEj6ygtjqbWL7duuRkDUs1Dl7XZYqjV6fRCxgzZss41yl6wpxfJZFqVhKzjMrSguFVAM7kCIvgwYKWqEVleiYSoh5gfPQNbfQDmXqs7zqrotJpAW54HVk+ZUkvWIZVjlgySnBHs2ju4vygVqIsl760rF2xdZCKojewOWdg9DkTXBaYA/5GZ9hi8PYMgxVx8RHKJ/WyNHby+lLZh8OcVt5OdfJo4/HoGrjxOoF0LZADR1d8atttZsitVI2wRFDFHKcrARCMTtKZaafaMKwVMKZZgl11DIrOge77cLfNH08oMfkOe2ZJ64zNm3EuB6emtJPEfUkb7CqhGtYsfF0oGqJ2GfynIAqKRGmaTTwHzu3F2xNYOEyEOAHyAH3VoST9C3dP7cOUOJWGcyUHm89lREiz0c1KBNu13122bwwRc0lAApOqMgzql7ejb/lMkUKe6Sy7Jensihqg/ugyjmwS6mnbknUUvIEXZiiLS+UhLDRdAzS+mS1kUSxY2EpxDJY="^M
script:^M
- ant build^M
- sonar-scanner^M
